spring:
  application:
    name: kafka-consumer-demo-one
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    default-schema: kafka
    liquibase-schema: public
    parameters:
      default-schema-prefix: kafka.
    database-change-log-table: kafka_log
    database-change-log-lock-table: kafka_lock
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: kafka
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: "user-group-one"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

logging:
  level:
    root: INFO
    org.one.demo: DEBUG

server:
  port: 8081

demo:
  kafka:
    topics:
      user-topic: user-topic
    group-id:
      user-group-id: user-group-one
